-- Create temporary table to store amr data
CREATE TEMPORARY TABLE tmp_amr(
	resultcode varchar not null,
	repyear numeric ,
	repcountry_id numeric,
	zoonosiscc numeric ,
	zoonosisst numeric ,
	zoonosis_id numeric ,
	zoonosist numeric ,
	cc numeric ,
	st numeric ,
	t numeric ,
	matrix_id numeric,
	totunitstested numeric ,
	totunitspositive numeric ,
	totsampunitstested numeric ,
	totsampunitspositive numeric ,
	sampunittype_id numeric,
	sampstage_id numeric,
	samporig_id varchar ,
	samptype_id numeric,
	sampcontext_id numeric,
	sampler_id numeric,
	progcode_code varchar ,
	progcode varchar ,
	progsampstrategy_id numeric,
	labisolcode varchar ,
	seqd numeric ,
	seqm numeric ,
	labtotisol numeric ,
	sampy numeric ,
	sampm numeric ,
	sampd numeric ,
	isoly numeric ,
	isolm numeric ,
	isold numeric ,
	analysisy numeric ,
	analysism numeric ,
	analysisd numeric ,
	anmethcode_id numeric,
	substance_id numeric,
	lowest_id numeric,
	highest_id numeric,
	mic_id numeric,
	cutoffvalue numeric ,
	esbl_code varchar ,
	ampc_code varchar ,
	carbapenem_code varchar,
	syntestcaz varchar ,
	syntestctx varchar ,
	syntestfep varchar ,
	percc varchar ,
	permlst varchar ,
	seqtech_code numeric,
	seqy numeric ,
	tracescode_code numeric,
	filename varchar,
	UNIQUE(filename, resultcode)
);
