-- ---------------------------------------------------- CREATE SCHEMA
CREATE SCHEMA efsa_consumption;

-- ---------------------------------------------------- FOOD CONSUMPTION DATA: CHRONIC
DROP TABLE IF EXISTS efsa_consumption.chronic;
CREATE TABLE efsa_consumption.chronic (
    id BIGSERIAL PRIMARY KEY,
	survey_start_year INTEGER,
	survey_name VARCHAR,
	population_group_l2 VARCHAR,
	exposure_hierarchy_l1 VARCHAR,
	exposure_hierarchy_l2 VARCHAR,
	exposure_hierarchy_l3 VARCHAR,
	exposure_hierarchy_l4 VARCHAR,
	exposure_hierarchy_l5 VARCHAR,
	exposure_hierarchy_l6 VARCHAR,
	exposure_hierarchy_l7 VARCHAR,
	number_of_subjects INTEGER,
	number_of_consumers INTEGER,
	mean_cag NUMERIC,
	standard_deviation_cag NUMERIC,
	percentile_5_cag NUMERIC,
	percentile_10_cag NUMERIC,
	median NUMERIC,
	percentile_95_cag NUMERIC,
	percentile_975_cag NUMERIC,
	percentile_99_cag NUMERIC,
	comment_cag TEXT,
	percentile_5_ccg NUMERIC,
	percentile_10_ccg NUMERIC,
	percentile_95_ccg NUMERIC,
	percentile_975_ccg NUMERIC,
	percentile_99_ccg NUMERIC,
	mean_ccg NUMERIC,
	standard_deviation_ccg NUMERIC,
	comment_ccg TEXT,
	percentile_5_cagkg NUMERIC,
	percentile_10_cagkg NUMERIC,
	percentile_95_cagkg NUMERIC,
	percentile_975_cagkg NUMERIC,
	percentile_99_cagkg NUMERIC,
	mean_cagkg NUMERIC,
	standard_deviation_cagkg NUMERIC,
	comment_cagkg TEXT,
	percentile_5_ccgkg NUMERIC,
	percentile_10_ccgkg NUMERIC,
	percentile_95_ccgkg NUMERIC,
	percentile_975_ccgkg NUMERIC,
	percentile_99_ccgkg NUMERIC,
	mean_ccgkg NUMERIC,
	standard_deviation_ccgkg NUMERIC,
	comment_ccgkg TEXT,
    survey_country_id INTEGER REFERENCES ontologies_efsa.country(id),
    mtx_id INTEGER REFERENCES ontologies_efsa.mtx(id),
	UNIQUE(survey_country_id, survey_start_year, survey_name, population_group_l2, exposure_hierarchy_l7)	
);

-- \copy efsa_consumption.chronic(survey_start_year,survey_name,population_group_l2,exposure_hierarchy_l1,exposure_hierarchy_l2,exposure_hierarchy_l3,exposure_hierarchy_l4,exposure_hierarchy_l5,exposure_hierarchy_l6,exposure_hierarchy_l7,number_of_subjects,number_of_consumers,mean_cag,standard_deviation_cag,percentile_5_cag,percentile_10_cag,median,percentile_95_cag,percentile_975_cag,percentile_99_cag,comment_cag,percentile_5_ccg,percentile_10_ccg,percentile_95_ccg,percentile_975_ccg,percentile_99_ccg,mean_ccg,standard_deviation_ccg,comment_ccg,percentile_5_cagkg,percentile_10_cagkg,percentile_95_cagkg,percentile_975_cagkg,percentile_99_cagkg,mean_cagkg,standard_deviation_cagkg,comment_cagkg,percentile_5_ccgkg,percentile_10_ccgkg,percentile_95_ccgkg,percentile_975_ccgkg,percentile_99_ccgkg,mean_ccgkg,standard_deviation_ccgkg,comment_ccgkg,survey_country_id,mtx_id) from 'C:\Users\hoend008\CHEFS Datascience\CHEFS\10. Consumption Data\Chronic\final\Chronic.csv' (header true, delimiter ',', format csv, encoding 'UTF-8');


-- ---------------------------------------------------- FOOD CONSUMPTION DATA: ACUTE
DROP TABLE IF EXISTS efsa_consumption.acute;
CREATE TABLE efsa_consumption.acute (
    id BIGSERIAL PRIMARY KEY,
	survey_start_year INTEGER,
	survey_name VARCHAR,
	population_group_l2 VARCHAR,
	exposure_hierarchy_l1 VARCHAR,
	exposure_hierarchy_l2 VARCHAR,
	exposure_hierarchy_l3 VARCHAR,
	exposure_hierarchy_l4 VARCHAR,
	exposure_hierarchy_l5 VARCHAR,
	exposure_hierarchy_l6 VARCHAR,
	exposure_hierarchy_l7 VARCHAR,
	number_of_days INTEGER,
	number_of_consuming_days INTEGER,
	mean_aag NUMERIC,
	standard_deviation_aag NUMERIC,
	percentile_5_aag NUMERIC,
	percentile_10_aag NUMERIC,
	median NUMERIC,
	percentile_95_aag NUMERIC,
	percentile_975_aag NUMERIC,
	percentile_99_aag NUMERIC,
	comment_aag TEXT,
	percentile_5_acg NUMERIC,
	percentile_10_acg NUMERIC,
	percentile_95_acg NUMERIC,
	percentile_975_acg NUMERIC,
	percentile_99_acg NUMERIC,
	mean_acg NUMERIC,
	standard_deviation_acg NUMERIC,
	comment_acg TEXT,
	percentile_5_aagkg NUMERIC,
	percentile_10_aagkg NUMERIC,
	percentile_95_aagkg NUMERIC,
	percentile_975_aagkg NUMERIC,
	percentile_99_aagkg NUMERIC,
	mean_aagkg NUMERIC,
	standard_deviation_aagkg NUMERIC,
	comment_aagkg TEXT,
	percentile_5_acgkg NUMERIC,
	percentile_10_acgkg NUMERIC,
	percentile_95_acgkg NUMERIC,
	percentile_975_acgkg NUMERIC,
	percentile_99_acgkg NUMERIC,
	mean_acgkg NUMERIC,
	standard_deviation_acgkg NUMERIC,
	comment_acgkg TEXT,
    survey_country_id INTEGER REFERENCES ontologies_efsa.country(id),
    mtx_id INTEGER REFERENCES ontologies_efsa.mtx(id),
	UNIQUE(survey_country_id, survey_start_year, survey_name, population_group_l2, exposure_hierarchy_l7)	
);

-- \copy efsa_consumption.acute(survey_start_year,survey_name,population_group_l2,exposure_hierarchy_l1,exposure_hierarchy_l2,exposure_hierarchy_l3,exposure_hierarchy_l4,exposure_hierarchy_l5,exposure_hierarchy_l6,exposure_hierarchy_l7,number_of_days,number_of_consuming_days,mean_aag,standard_deviation_aag,percentile_5_aag,percentile_10_aag,median,percentile_95_aag,percentile_975_aag,percentile_99_aag,comment_aag,percentile_5_acg,percentile_10_acg,percentile_95_acg,percentile_975_acg,percentile_99_acg,mean_acg,standard_deviation_acg,comment_acg,percentile_5_aagkg,percentile_10_aagkg,percentile_95_aagkg,percentile_975_aagkg,percentile_99_aagkg,mean_aagkg,standard_deviation_aagkg,comment_aagkg,percentile_5_acgkg,percentile_10_acgkg,percentile_95_acgkg,percentile_975_acgkg,percentile_99_acgkg,mean_acgkg,standard_deviation_acgkg,comment_acgkg,survey_country_id,mtx_id) from 'C:\Users\hoend008\CHEFS Datascience\CHEFS\10. Consumption Data\Acute\final\Acute.csv' (header true, delimiter ',', format csv, encoding 'UTF-8');


-- ---------------------------------------------------- FOOD CONSUMPTION DATA: CHRONIC GENDER
DROP TABLE IF EXISTS efsa_consumption.chronic_gender;
CREATE TABLE efsa_consumption.chronic_gender (
    id BIGSERIAL PRIMARY KEY,
	survey_start_year INTEGER,
	survey_name VARCHAR,
	population_group_l2 VARCHAR,
	exposure_hierarchy_l1 VARCHAR,
	exposure_hierarchy_l2 VARCHAR,
	exposure_hierarchy_l3 VARCHAR,
	exposure_hierarchy_l4 VARCHAR,
	exposure_hierarchy_l5 VARCHAR,
	exposure_hierarchy_l6 VARCHAR,
	exposure_hierarchy_l7 VARCHAR,
	gender VARCHAR,
	number_of_subjects INTEGER,
	number_of_consumers INTEGER,
	mean_cag NUMERIC,
	standard_deviation_cag NUMERIC,
	percentile_5_cag NUMERIC,
	percentile_10_cag NUMERIC,
	median NUMERIC,
	percentile_95_cag NUMERIC,
	percentile_975_cag NUMERIC,
	percentile_99_cag NUMERIC,
	comment_cag TEXT,
	percentile_5_ccg NUMERIC,
	percentile_10_ccg NUMERIC,
	percentile_95_ccg NUMERIC,
	percentile_975_ccg NUMERIC,
	percentile_99_ccg NUMERIC,
	mean_ccg NUMERIC,
	standard_deviation_ccg NUMERIC,
	comment_ccg TEXT,
	percentile_5_cagkg NUMERIC,
	percentile_10_cagkg NUMERIC,
	percentile_95_cagkg NUMERIC,
	percentile_975_cagkg NUMERIC,
	percentile_99_cagkg NUMERIC,
	mean_cagkg NUMERIC,
	standard_deviation_cagkg NUMERIC,
	comment_cagkg TEXT,
	percentile_5_ccgkg NUMERIC,
	percentile_10_ccgkg NUMERIC,
	percentile_95_ccgkg NUMERIC,
	percentile_975_ccgkg NUMERIC,
	percentile_99_ccgkg NUMERIC,
	mean_ccgkg NUMERIC,
	standard_deviation_ccgkg NUMERIC,
	comment_ccgkg TEXT,
    survey_country_id INTEGER REFERENCES ontologies_efsa.country(id),
    mtx_id INTEGER REFERENCES ontologies_efsa.mtx(id),
	UNIQUE(survey_country_id, survey_start_year, survey_name, population_group_l2, exposure_hierarchy_l7, gender)	
);

-- \copy efsa_consumption.chronic_gender(survey_start_year,survey_name,population_group_l2,exposure_hierarchy_l1,exposure_hierarchy_l2,exposure_hierarchy_l3,exposure_hierarchy_l4,exposure_hierarchy_l5,exposure_hierarchy_l6,exposure_hierarchy_l7,gender,number_of_subjects,number_of_consumers,mean_cag,standard_deviation_cag,percentile_5_cag,percentile_10_cag,median,percentile_95_cag,percentile_975_cag,percentile_99_cag,comment_cag,percentile_5_ccg,percentile_10_ccg,percentile_95_ccg,percentile_975_ccg,percentile_99_ccg,mean_ccg,standard_deviation_ccg,comment_ccg,percentile_5_cagkg,percentile_10_cagkg,percentile_95_cagkg,percentile_975_cagkg,percentile_99_cagkg,mean_cagkg,standard_deviation_cagkg,comment_cagkg,percentile_5_ccgkg,percentile_10_ccgkg,percentile_95_ccgkg,percentile_975_ccgkg,percentile_99_ccgkg,mean_ccgkg,standard_deviation_ccgkg,comment_ccgkg,survey_country_id,mtx_id) from 'C:\Users\hoend008\CHEFS Datascience\CHEFS\10. Consumption Data\Chronic Gender\final\Chronic Gender.csv' (header true, delimiter ',', format csv, encoding 'UTF-8');


-- ---------------------------------------------------- FOOD CONSUMPTION DATA: ACUTE GENDER
DROP TABLE IF EXISTS efsa_consumption.acute_gender;
CREATE TABLE efsa_consumption.acute_gender (
    id BIGSERIAL PRIMARY KEY,
	survey_start_year INTEGER,
	survey_name VARCHAR,
	population_group_l2 VARCHAR,
	exposure_hierarchy_l1 VARCHAR,
	exposure_hierarchy_l2 VARCHAR,
	exposure_hierarchy_l3 VARCHAR,
	exposure_hierarchy_l4 VARCHAR,
	exposure_hierarchy_l5 VARCHAR,
	exposure_hierarchy_l6 VARCHAR,
	exposure_hierarchy_l7 VARCHAR,
	gender VARCHAR,
	number_of_days INTEGER,
	number_of_consuming_days INTEGER,
	mean_aag NUMERIC,
	standard_deviation_aag NUMERIC,
	percentile_5_aag NUMERIC,
	percentile_10_aag NUMERIC,
	median NUMERIC,
	percentile_95_aag NUMERIC,
	percentile_975_aag NUMERIC,
	percentile_99_aag NUMERIC,
	comment_aag TEXT,
	percentile_5_acg NUMERIC,
	percentile_10_acg NUMERIC,
	percentile_95_acg NUMERIC,
	percentile_975_acg NUMERIC,
	percentile_99_acg NUMERIC,
	mean_acg NUMERIC,
	standard_deviation_acg NUMERIC,
	comment_acg TEXT,
	percentile_5_aagkg NUMERIC,
	percentile_10_aagkg NUMERIC,
	percentile_95_aagkg NUMERIC,
	percentile_975_aagkg NUMERIC,
	percentile_99_aagkg NUMERIC,
	mean_aagkg NUMERIC,
	standard_deviation_aagkg NUMERIC,
	comment_aagkg TEXT,
	percentile_5_acgkg NUMERIC,
	percentile_10_acgkg NUMERIC,
	percentile_95_acgkg NUMERIC,
	percentile_975_acgkg NUMERIC,
	percentile_99_acgkg NUMERIC,
	mean_acgkg NUMERIC,
	standard_deviation_acgkg NUMERIC,
	comment_acgkg TEXT,
    survey_country_id INTEGER REFERENCES ontologies_efsa.country(id),
    mtx_id INTEGER REFERENCES ontologies_efsa.mtx(id),
	UNIQUE(survey_country_id, survey_start_year, survey_name, population_group_l2, exposure_hierarchy_l7, gender)	
);

-- \copy efsa_consumption.acute_gender(survey_start_year,survey_name,population_group_l2,exposure_hierarchy_l1,exposure_hierarchy_l2,exposure_hierarchy_l3,exposure_hierarchy_l4,exposure_hierarchy_l5,exposure_hierarchy_l6,exposure_hierarchy_l7,gender,number_of_days,number_of_consuming_days,mean_aag,standard_deviation_aag,percentile_5_aag,percentile_10_aag,median,percentile_95_aag,percentile_975_aag,percentile_99_aag,comment_aag,percentile_5_acg,percentile_10_acg,percentile_95_acg,percentile_975_acg,percentile_99_acg,mean_acg,standard_deviation_acg,comment_acg,percentile_5_aagkg,percentile_10_aagkg,percentile_95_aagkg,percentile_975_aagkg,percentile_99_aagkg,mean_aagkg,standard_deviation_aagkg,comment_aagkg,percentile_5_acgkg,percentile_10_acgkg,percentile_95_acgkg,percentile_975_acgkg,percentile_99_acgkg,mean_acgkg,standard_deviation_acgkg,comment_acgkg,survey_country_id,mtx_id) from 'C:\Users\hoend008\CHEFS Datascience\CHEFS\10. Consumption Data\Acute Gender\final\Acute Gender.csv' (header true, delimiter ',', format csv, encoding 'UTF-8');